const beginnerQuestions = [
  {
    id: 'B1',
    category: '基础查询',
    title: '查询所有员工',
    description: '查询 employees 表中的所有员工信息。',
    difficulty: '简单',
    tables: ['employees'],
    hint: '使用 SELECT * 从 employees 表读取全部记录。',
    solution: 'SELECT *\nFROM employees;',
  },
  {
    id: 'B2',
    category: '基础查询',
    title: '查询技术部员工',
    description: '查询 department_id 为 1 的员工姓名和薪资。',
    difficulty: '简单',
    tables: ['employees'],
    hint: '使用 WHERE 过滤 department_id。',
    solution: 'SELECT name, salary\nFROM employees\nWHERE department_id = 1;',
  },
  {
    id: 'B3',
    category: '排序分页',
    title: '按薪资倒序',
    description: '查询员工姓名、薪资，并按薪资从高到低排序。',
    difficulty: '简单',
    tables: ['employees'],
    hint: 'ORDER BY salary DESC。',
    solution: 'SELECT name, salary\nFROM employees\nORDER BY salary DESC;',
  },
  {
    id: 'B4',
    category: '聚合统计',
    title: '统计员工人数',
    description: '统计 employees 表中的员工总数。',
    difficulty: '简单',
    tables: ['employees'],
    hint: '使用 COUNT(*)。',
    solution: 'SELECT COUNT(*) AS employee_count\nFROM employees;',
  },
  {
    id: 'B5',
    category: '聚合统计',
    title: '计算平均薪资',
    description: '计算全部员工的平均薪资。',
    difficulty: '简单',
    tables: ['employees'],
    hint: '使用 AVG(salary)。',
    solution: 'SELECT AVG(salary) AS avg_salary\nFROM employees;',
  },
  {
    id: 'B6',
    category: '分组聚合',
    title: '部门员工数',
    description: '按部门统计员工数量。',
    difficulty: '简单',
    tables: ['employees'],
    hint: '按 department_id 分组。',
    solution: 'SELECT department_id, COUNT(*) AS employee_count\nFROM employees\nGROUP BY department_id;',
  },
  {
    id: 'B7',
    category: '分组聚合',
    title: '部门平均薪资',
    description: '统计每个部门的平均薪资。',
    difficulty: '简单',
    tables: ['employees'],
    hint: 'GROUP BY department_id 后计算 AVG(salary)。',
    solution: 'SELECT department_id, AVG(salary) AS avg_salary\nFROM employees\nGROUP BY department_id;',
  },
  {
    id: 'B8',
    category: '多表关联',
    title: '员工所属部门',
    description: '查询员工姓名、部门名称和部门所在地。',
    difficulty: '简单',
    tables: ['employees', 'departments'],
    hint: 'employees.department_id 关联 departments.id。',
    solution: 'SELECT e.name, d.name AS department_name, d.location\nFROM employees e\nJOIN departments d ON e.department_id = d.id;',
  },
  {
    id: 'B9',
    category: '多表关联',
    title: '订单用户信息',
    description: '查询订单 ID、用户名和订单金额。',
    difficulty: '简单',
    tables: ['orders', 'users'],
    hint: 'orders.user_id 关联 users.id。',
    solution: 'SELECT o.id AS order_id, u.username, o.total_amount\nFROM orders o\nJOIN users u ON o.user_id = u.id;',
  },
  {
    id: 'B10',
    category: '多表关联',
    title: '订单商品信息',
    description: '查询订单 ID、商品名称、购买数量和订单金额。',
    difficulty: '简单',
    tables: ['orders', 'products'],
    hint: 'orders.product_id 关联 products.id。',
    solution: 'SELECT o.id AS order_id, p.name AS product_name, o.quantity, o.total_amount\nFROM orders o\nJOIN products p ON o.product_id = p.id;',
  },
  {
    id: 'B11',
    category: '条件筛选',
    title: '高薪员工',
    description: '查询薪资大于 20000 的员工。',
    difficulty: '简单',
    tables: ['employees'],
    hint: 'WHERE salary > 20000。',
    solution: 'SELECT *\nFROM employees\nWHERE salary > 20000;',
  },
  {
    id: 'B12',
    category: '条件筛选',
    title: '电子产品列表',
    description: '查询 category 为“电子产品”的商品。',
    difficulty: '简单',
    tables: ['products'],
    hint: '字符串条件需要使用引号。',
    solution: "SELECT *\nFROM products\nWHERE category = '电子产品';",
  },
  {
    id: 'B13',
    category: '聚合统计',
    title: '商品库存汇总',
    description: '按商品类别统计总库存。',
    difficulty: '简单',
    tables: ['products'],
    hint: '按 category 分组并 SUM(stock)。',
    solution: 'SELECT category, SUM(stock) AS total_stock\nFROM products\nGROUP BY category;',
  },
  {
    id: 'B14',
    category: '分组过滤',
    title: '订单金额超过 5000 的用户',
    description: '统计每个用户的订单总金额，并筛选总金额大于 5000 的用户。',
    difficulty: '中等',
    tables: ['orders'],
    hint: '聚合后的过滤使用 HAVING。',
    solution: 'SELECT user_id, SUM(total_amount) AS total_amount\nFROM orders\nGROUP BY user_id\nHAVING SUM(total_amount) > 5000;',
  },
  {
    id: 'B15',
    category: '多表关联',
    title: '用户购买商品明细',
    description: '查询用户名、商品名称、购买数量和订单金额。',
    difficulty: '中等',
    tables: ['users', 'orders', 'products'],
    hint: 'users、orders、products 三表关联。',
    solution: 'SELECT u.username, p.name AS product_name, o.quantity, o.total_amount\nFROM orders o\nJOIN users u ON o.user_id = u.id\nJOIN products p ON o.product_id = p.id;',
  },
];

const advancedQuestions = [
  ['1.1', '分组排序', '每门课程的成绩排名', '查询每门课程内学生成绩的排名。', '中等', ['student_courses'], '使用窗口函数 RANK() 或 DENSE_RANK()，按 course 分区。', 'SELECT course, score, y,\n       RANK() OVER (PARTITION BY course ORDER BY score DESC) AS ranking\nFROM student_courses;'],
  ['1.2', '分组排序', '年度用户价值排名', '查询每年用户价值排名。', '中等', ['user_values'], '按 year 分区，按 value 倒序排名。', 'SELECT year, user_id, value,\n       RANK() OVER (PARTITION BY year ORDER BY value DESC) AS ranking\nFROM user_values;'],
  ['1.3-1', '分组排序', '学生各科成绩排名', '查询每年每个科目的学生成绩排名。', '中等', ['student_scores'], '按 year、subject 分区。', 'SELECT year, subject, student, score,\n       RANK() OVER (PARTITION BY year, subject ORDER BY score DESC) AS ranking\nFROM student_scores;'],
  ['1.4', '分组排序', '第二高薪水', '查询员工表中的第二高薪水。', '简单', ['employee_salary'], '可使用去重排序加 LIMIT/OFFSET。', 'SELECT DISTINCT salary\nFROM employee_salary\nORDER BY salary DESC\nLIMIT 1 OFFSET 1;'],
  ['1.5', '用户行为', '用户最近一次订单', '查询每个用户最近一次购买记录。', '中等', ['orders_detail'], '用 ROW_NUMBER() 找每个 user_id 最新的一条订单。', 'SELECT *\nFROM (\n  SELECT o.*,\n         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY purchase_time DESC) AS rn\n  FROM orders_detail o\n) t\nWHERE rn = 1;'],
  ['1.6', '聚合统计', '中位数计算', '计算 median_numbers 表中数字的中位数。', '困难', ['median_numbers'], '用窗口函数计算行号和总行数，再取中间位置。', 'SELECT AVG(num) AS median\nFROM (\n  SELECT num,\n         ROW_NUMBER() OVER (ORDER BY num) AS rn,\n         COUNT(*) OVER () AS cnt\n  FROM median_numbers\n) t\nWHERE rn IN (FLOOR((cnt + 1) / 2), FLOOR((cnt + 2) / 2));'],
  ['2.1', '连续问题', '用户点击会话识别', '根据点击时间识别用户连续点击会话。', '困难', ['click_log'], '先用 LAG 计算与上一次点击的间隔，再累加会话起点。', 'SELECT user_id, click_time,\n       SUM(is_new_session) OVER (PARTITION BY user_id ORDER BY click_time) AS session_id\nFROM (\n  SELECT user_id, click_time,\n         CASE WHEN click_time - LAG(click_time) OVER (PARTITION BY user_id ORDER BY click_time) <= 60 THEN 0 ELSE 1 END AS is_new_session\n  FROM click_log\n) t;'],
  ['2.2', '连续问题', '最长连胜天数', '计算每个用户最长连续获胜天数。', '困难', ['matches'], '筛选 win 后用日期减行号构造连续分组。', "SELECT uid, MAX(win_days) AS max_win_days\nFROM (\n  SELECT uid, COUNT(*) AS win_days\n  FROM (\n    SELECT uid, dt,\n           DATE_SUB(dt, INTERVAL ROW_NUMBER() OVER (PARTITION BY uid ORDER BY dt) DAY) AS grp\n    FROM matches\n    WHERE res = 'win'\n  ) t\n  GROUP BY uid, grp\n) g\nGROUP BY uid;"],
  ['2.3', '连续问题', '连续登录天数', '查询每个用户的最长连续登录天数。', '中等', ['dau'], '对登录日期去重后用日期减行号分组。', 'SELECT user_id, MAX(days) AS max_login_days\nFROM (\n  SELECT user_id, COUNT(*) AS days\n  FROM (\n    SELECT user_id, login_date,\n           DATE_SUB(login_date, INTERVAL ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) DAY) AS grp\n    FROM dau\n  ) t\n  GROUP BY user_id, grp\n) g\nGROUP BY user_id;'],
  ['2.5', '连续问题', '连续出现的数字', '找出至少连续出现三次的数字。', '中等', ['consecutive_logs'], '用 LAG/LEAD 比较前后记录。', 'SELECT DISTINCT num\nFROM (\n  SELECT num,\n         LAG(num) OVER (ORDER BY id) AS prev_num,\n         LEAD(num) OVER (ORDER BY id) AS next_num\n  FROM consecutive_logs\n) t\nWHERE num = prev_num AND num = next_num;'],
  ['2.6', '连续问题', '比昨天温度更高', '查询比前一天温度更高的记录。', '简单', ['weather'], '自连接相邻日期，比较 temperature。', 'SELECT w1.id\nFROM weather w1\nJOIN weather w2 ON DATEDIFF(w1.recordDate, w2.recordDate) = 1\nWHERE w1.temperature > w2.temperature;'],
  ['3.1', '行列转换', '拆分用户兴趣标签', '将用户兴趣标签按逗号拆分后统计每个标签人数。', '困难', ['user_interests'], 'MySQL 可用递归 CTE 或 JSON_TABLE 处理拆分。', "WITH RECURSIVE split_tags AS (\n  SELECT user_id,\n         SUBSTRING_INDEX(interests, ',', 1) AS tag,\n         SUBSTRING(interests, LENGTH(SUBSTRING_INDEX(interests, ',', 1)) + 2) AS rest\n  FROM user_interests\n  UNION ALL\n  SELECT user_id,\n         SUBSTRING_INDEX(rest, ',', 1),\n         SUBSTRING(rest, LENGTH(SUBSTRING_INDEX(rest, ',', 1)) + 2)\n  FROM split_tags\n  WHERE rest <> ''\n)\nSELECT tag, COUNT(DISTINCT user_id) AS user_count\nFROM split_tags\nGROUP BY tag;"],
  ['3.2-1', '行列转换', '行转列', '将 row2col 表中 c、d、e 三类属性转成列。', '中等', ['row2col'], '使用条件聚合。', "SELECT col1,\n       MAX(CASE WHEN col2 = 'c' THEN col3 END) AS c,\n       MAX(CASE WHEN col2 = 'd' THEN col3 END) AS d,\n       MAX(CASE WHEN col2 = 'e' THEN col3 END) AS e\nFROM row2col\nGROUP BY col1;"],
  ['3.2-2', '行列转换', '列转行', '将 col2row 表中的 col_A、col_B 转换为多行。', '中等', ['col2row'], '使用 UNION ALL。', "SELECT a, 'A' AS col_name, col_A AS val FROM col2row\nUNION ALL\nSELECT a, 'B' AS col_name, col_B AS val FROM col2row;"],
  ['4.1', '条件聚合', '各课程高分人数', '统计每门课程成绩大于等于 90 的学生数。', '简单', ['exam_scores'], 'SUM(CASE WHEN score >= 90 THEN 1 ELSE 0 END)。', 'SELECT cid,\n       SUM(CASE WHEN score >= 90 THEN 1 ELSE 0 END) AS high_score_count\nFROM exam_scores\nGROUP BY cid;'],
  ['5.1', '用户行为', '每日活跃用户', '统计每日登录用户数。', '简单', ['user_login_detail'], '按 log_date 分组，COUNT(DISTINCT user_id)。', 'SELECT log_date, COUNT(DISTINCT user_id) AS dau\nFROM user_login_detail\nGROUP BY log_date\nORDER BY log_date;'],
  ['5.2', '累计区间', '同时在线人数峰值', '计算登录登出日志中的同时在线人数峰值。', '困难', ['login_status'], '登录记 +1，登出记 -1，按时间累加。', 'SELECT MAX(online_count) AS peak_online\nFROM (\n  SELECT ts,\n         SUM(delta) OVER (ORDER BY ts, delta DESC) AS online_count\n  FROM (\n    SELECT login_ts AS ts, 1 AS delta FROM login_status\n    UNION ALL\n    SELECT logout_ts AS ts, -1 AS delta FROM login_status\n  ) e\n) t;'],
  ['5.3', '累计区间', '直播间在线人数', '统计直播间每个时间点的在线人数变化。', '困难', ['live_room_logs'], '进入记 +1，离开记 -1，按 room_id 和时间累加。', 'SELECT room_id, ts,\n       SUM(delta) OVER (PARTITION BY room_id ORDER BY ts, delta DESC) AS online_count\nFROM (\n  SELECT room_id, enter_time AS ts, 1 AS delta FROM live_room_logs\n  UNION ALL\n  SELECT room_id, leave_time AS ts, -1 AS delta FROM live_room_logs\n) e;'],
  ['6.1', '留存分析', '次日留存率', '计算首次登录后的次日留存率。', '中等', ['player_activity'], '先找每个玩家首次日期，再判断次日是否出现。', 'WITH first_login AS (\n  SELECT player_id, MIN(event_date) AS first_date\n  FROM player_activity\n  GROUP BY player_id\n)\nSELECT ROUND(COUNT(a.player_id) / COUNT(f.player_id), 2) AS retention_rate\nFROM first_login f\nLEFT JOIN player_activity a\n  ON a.player_id = f.player_id\n AND a.event_date = DATE_ADD(f.first_date, INTERVAL 1 DAY);'],
  ['6.2', '留存分析', 'DAU 统计', '统计 dau_events 表每日活跃用户数。', '简单', ['dau_events'], '按 login_date 统计去重用户数。', 'SELECT login_date, COUNT(DISTINCT user_id) AS dau\nFROM dau_events\nGROUP BY login_date\nORDER BY login_date;'],
  ['7.1', '社交关系', '好友申请通过数', '统计每个用户收到并接受的好友申请数量。', '简单', ['friend_requests'], '按 accepter_id 分组。', 'SELECT accepter_id AS user_id, COUNT(*) AS accepted_count\nFROM friend_requests\nGROUP BY accepter_id;'],
  ['7.2', '社交关系', '互相关注用户对', '找出互相关注的用户对。', '中等', ['followers'], '自连接并限定 from_user < to_user 去重。', 'SELECT f1.from_user AS user_a, f1.to_user AS user_b\nFROM followers f1\nJOIN followers f2\n  ON f1.from_user = f2.to_user\n AND f1.to_user = f2.from_user\nWHERE f1.from_user < f1.to_user;'],
  ['7.3', '社交关系', '每人好友数', '根据好友接受表统计每个用户的好友数量。', '中等', ['accepted_friends'], '申请方和接受方都要计入好友关系。', 'SELECT user_id, COUNT(DISTINCT friend_id) AS friend_count\nFROM (\n  SELECT requester_id AS user_id, accepter_id AS friend_id FROM accepted_friends\n  UNION ALL\n  SELECT accepter_id AS user_id, requester_id AS friend_id FROM accepted_friends\n) t\nGROUP BY user_id;'],
  ['7.4', '社交关系', '好友步数排行', '查询每个用户好友的步数排名。', '中等', ['user_friends', 'user_steps'], '先关联好友步数，再按 user_id 分区排名。', 'SELECT f.user_id, f.friend_id, s.steps,\n       RANK() OVER (PARTITION BY f.user_id ORDER BY s.steps DESC) AS step_rank\nFROM user_friends f\nJOIN user_steps s ON f.friend_id = s.user_id;'],
  ['8.1', '精选杂题', '指定日期产品价格', '查询每个产品在 2019-08-16 的价格。', '中等', ['product_prices'], '找出目标日期前最近一次价格变更。', "SELECT product_id, new_price AS price\nFROM (\n  SELECT product_id, new_price,\n         ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY change_date DESC) AS rn\n  FROM product_prices\n  WHERE change_date <= '2019-08-16'\n) t\nWHERE rn = 1;"],
  ['8.3', '精选杂题', '股票价格波动', '计算每条股票价格与上一条价格的差值。', '中等', ['stock_prices'], '使用 LAG(price)。', 'SELECT code, ts, price,\n       price - LAG(price) OVER (PARTITION BY code ORDER BY ts) AS price_diff\nFROM stock_prices;'],
  ['8.4', '精选杂题', '同 IP 多账号登录', '找出同一 IP 登录过的不同用户数。', '简单', ['login_logs'], '按 ip 分组统计 DISTINCT user_id。', 'SELECT ip, COUNT(DISTINCT user_id) AS user_count\nFROM login_logs\nGROUP BY ip\nHAVING COUNT(DISTINCT user_id) > 1;'],
  ['8.5', '精选杂题', '作者浏览自己的文章', '找出浏览过自己文章的作者。', '简单', ['article_views'], 'author_id 等于 viewer_id。', 'SELECT DISTINCT author_id AS id\nFROM article_views\nWHERE author_id = viewer_id;'],
].map(([id, category, title, description, difficulty, tables, hint, solution]) => ({
  id,
  category,
  title,
  description,
  difficulty,
  tables,
  hint,
  solution,
}));

module.exports = [...beginnerQuestions, ...advancedQuestions];
